name: "Dummy"
on:
  workflow_dispatch:
    inputs:
      sleep_time:
        description: "sleep for"
        required: true
        default: 1
      tag:
        description: "Aditional tag"
        required: true
        default: x64


permissions:
  packages: write


jobs:
  packages:
    name: "Do nothing, really"
    runs-on:
      - self-hosted
      - ${{ github.event.inputs.tag }}
    steps:
      - name: "Just print some info"
        shell: bash
        run: |
          hostname
          uname -a
          df -h
          whoami
          sleep ${{ github.event.inputs.sleep_time }}

